version: "3.7"

services:
  besu-node1:
    image: hyperledger/besu:23.10.2
    container_name: besu-node1
    command: [
      "--network=dev",
      "--miner-enabled",
      "--miner-coinbase=0x0000000000000000000000000000000000000000",
      "--rpc-http-enabled",
      "--rpc-http-host=0.0.0.0",
      "--host-allowlist=*",
      "--rpc-http-cors-origins=*",
      "--rpc-ws-enabled",
      "--rpc-ws-host=0.0.0.0",
      "--data-path=/var/lib/besu",
      "--rpc-http-api=ETH,NET,WEB3,CLIQUE,IBFT,ADMIN,TXPOOL,DEBUG,MINER,PERM,EEA,PRIV"
    ]
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - besu-node1-data:/var/lib/besu

volumes:
  besu-node1-data: 