caliper:
  blockchain: ethereum
  sutOptions:
    chainId: 2018
    networkId: 2018
    hardfork: istanbul
    gasLimit: 8000000
    gasPrice: 0
    host: "http://localhost:8545"
    privateKey: "0x8f2a55949018a6a4a6d3c2b5a6e5c2c5b9e5c2c5b9e5c2c5b9e5c2c5b9e5c2c5"
    defaultAccount: "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
  contracts:
    CBSDRegistry:
      abi: "./artifacts/contracts/CBSDRegistry.sol/CBSDRegistry.json"
      bytecode: "./artifacts/contracts/CBSDRegistry.sol/CBSDRegistry.json" 